import Head from "next/head";
import styled from "styled-components";
import client from "../apollo";
import HOME from "../queries/homepage";
import About from "../components/homepage/About";
import Stack from "../components/homepage/Technologies";
import Jobs from "../components/homepage/Jobs";
import { device } from "../styles/theme";

const Container = styled.div`
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  position: relative;
  padding-top: 4rem;
  top: 0;
  left: 0;
  transition: 0.5s;

  @media ${device.tablet} {
    padding: 2rem 1rem 3rem 1rem;

    && p {
      font-size: 1.2rem;
    }

    && h1 {
      font-size: 3rem;
    }
  }
}
`;

export default function Home({ home }) {
  return (
    <Container>
      <Head>
        <title>{`${home.About.firstName}'s website.`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <About description={home.About.description} />
      <Stack techs={home.Body.Stack} />
      <Jobs jobList={home.Body.Job} />
    </Container>
  );
}

export async function getStaticProps(ctx) {
  const { data } = await client.query({
    query: HOME,
  });

  return {
    props: {
      home: data.homepage,
    },
    revalidate: 1,
  };
}
